### PR TITLE
Use empty string instead of null for lack of policy

### PR DESCRIPTION
**Pull request by estark37**
This addresses issue #21.

### CODE REVIEW

**Comment by estark37** [comment]
@jeisinger @annevk PTAL?

**Comment by jeisinger** [comment]
LGTM

**Comment by annevk** [comment]
Instead of "" it might be clearer to say "the empty string".

**Comment by estark37** [comment]
@annevk: done.

**Comment by annevk** [comment]
Thank you, LGTM.

**Pull request merged**
