### PR TITLE
Clarify referrer rules for inline styles

### PR DESCRIPTION
**Pull request by jeisinger**
@bzbarsky wdyt

### CODE REVIEW

**Comment by bzbarsky** [comment]
This seems ok as far as it goes, but the claim that "Otherwise, a CSS declaration block that is part of an element's inline style properties is responsible for the request" is just not true for `<body background="whatever">` and similar...

**Comment by jdm** [comment]
Can you ensure that web-platform-tests has tests covering this?

**Comment by jeisinger** [comment]
Yes, I'll work on WPT tests before landing this in blink

**Comment by jeisinger** [comment]
wpt is here: https://github.com/w3c/web-platform-tests/pull/5160

will polish the spec test to reflect this

**Comment by jeisinger** [comment]
@bzbarsky ptal

**Comment by tabatkins** [comment]
Looks ok to me with a fairly quick readthrough :+1:

**Pull request merged**
