### PR TITLE
Editorial: export terms for Fetch

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
Note that the generated resource is not ideal here. I tried to solve those problems in #79 so you might want to merge that first.

**Comment by annevk** [comment]
This PR coupled with https://github.com/tabatkins/bikeshed/issues/855 will make it feasible for Fetch to no longer use an "anchors" block for Referrer Policy links.

**Comment by annevk** [comment]
I'll rebase this.

**Comment by annevk** [comment]
Done. By the way, why is there both a master and gh-pages branch?

**Comment by estark37** [comment]
Thanks @annevk! The gh-pages branch makes the spec accessible at https://w3c.github.io/webappsec-referrer-policy/

**Comment by annevk** [comment]
I understand, but wouldn't it be easier to just have a gh-pages branch then and do away with master?

**Comment by estark37** [comment]
Not sure -- that's the way it's been set up since before my time, and seems to be the way other webappsec specs are set up too. @mikewest @jeisinger? Maybe it's sometimes convenient to be able to put changes on master without updating the editor's draft right away?

**Pull request merged**
