### PR TITLE
Add a paragraph talking about how to integrate with CSS

### PR DESCRIPTION
**Pull request by jeisinger**
@annevk @estark37 @tabatkins 

ptal

### CODE REVIEW

**Comment by jeisinger** [comment]
addresses #5

**Comment by tabatkins** [comment]
You probably have a good reason, but why does this specify a different policy than what CSS Fonts specifies?  (Fonts says the referrer should be the stylesheets url, you're saying it should be the containing document's url.)  What's the pro/con of doing it the way you specify vs what Fonts says?

**Comment by jeisinger** [comment]
Pro of mine is: does what all other requests do. CSS fonts also sets the
origin to the containing document. The stylesheet has no referrer policy,
but the doc has one

Pro of CSS fonts: none afaik. I asked the person who wrote the blink
implementation, and filed a spec bug, and asked you, but nobody knew any
particular reason.

**Comment by tabatkins** [comment]
Sounds reasonable, especially the fact that stylesheets don't have a referrer policy.

Can you see if impls are willing to change @font-face loading to harmonize with this? We can change the spec easily then.

**Comment by annevk** [comment]
The referrer for CSS subresources should be that of the stylesheet. Just like the base URL is the URL of the stylesheet. I think most implementations have behaved this way ever since CSS was invented.

**Comment by annevk** [comment]
(This should be defined in CSS though, ideally...)

**Comment by jeisinger** [comment]
meh

in the end, I guess that means that stylesheets should track their own referrer policy, and we can probably only deliver it via the referrer header.

**Comment by annevk** [comment]
That makes sense, I guess we could say that they inherit one from the document. All this would be easier to define if CSS had some infrastructure around its basic model.

**Comment by jeisinger** [comment]
hum, so if you load it via <link rel=stylesheet referrerpolicy=origin> but the document's referrerpolicy is never, which one should be inherited?

**Comment by jeisinger** [comment]
in other words, I'd rather not inherit from the document.

**Comment by annevk** [comment]
I can't quite parse that sentence. The suggestion was to inherit if no policy was specified through HTTP.

**Pull request closed without merging**
