### PR TITLE
Clarify that modifying img.referrerPolicy is not a relevant mutation

### LINKED ISSUE #33: Should the referrerPolicy attribute be part of the "relevant mutations" for HTMLImageElement?
https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations defines a set of mutations that cause the image element to request the image data. There's no text in this specification that indicates how modifications to the `referrerPolicy` attribute are supposed to affect `` after a load has previously been started (whether it has previously completed or not).

### PR DESCRIPTION
**Pull request by jeisinger**
@estark37 @annevk 

fixes #33

### CODE REVIEW

**Comment by annevk** [comment]
LGTM

**Comment by annevk** [comment]
Per @tungmangtdh3 suggested change to web-platform-tests I now wonder if maybe it would be better if this did trigger a rerun. @zcorpan, is `` really that synchronous? It might be surprising that
```
img.referrerPolicy = y
img.src = x
```
and
```
img.src = x
img.referrerPolicy = y
```
have different results.

**Comment by tungmangtdh3** [comment]
I tried with Firefox nightly
img.referrerPolicy = y
img.src = x
Pass.
img.src = x
img.referrerPolicy = y
Failed.
I have not tried to compare result of 2 cases with Google Canary and Opera.

**Comment by jeisinger** [comment]
I agree that this might be confusing, but once the request hit the network, modifying the policy is too late, so just resending the request won't unleak the referrer.

**Comment by annevk** [comment]
Does `` end up creating two requests for the above scenarios for attributes that are relevant mutations?

**Comment by jeisinger** [comment]
hum, setting e.g. crossOrigin to "anonymous" doesn't trigger a second request.

**Comment by jeisinger** [comment]
@zcorpan can you advise what the right thing to do here is?

**Comment by zcorpan** [comment]
Per spec the "update the image data" algorithm starts synchronously when a relevant mutation happens, but it only changes the image synchronously if the `img` has only `src` (no `srcset` or `picture` parent) *and* that URL is in the image cache. Otherwise, it "awaits a stable state" (microtask) to continue the algorithm, which lets the current script complete and set all attributes it wants before the actual request is created. So the order in which a script sets src/crossOrigin/referrerPolicy should not matter per spec.

**Comment by zcorpan** [comment]
cc @yoavweiss

**Comment by jeisinger** [comment]
ptal

**Comment by zcorpan** [comment]
You need to change `index.src.html` (and regen).

I don't have an opinion yet on whether this should be a relevant mutation or not. It does not make any difference for setting things up initially in a script. If it is a relevant mutation, then changing `referrerPolicy` *later* will cause "update the image data" to re-run.

That algorithm doesn't currently know about `referrerPolicy` (e.g. it doesn't use it as part of the key in the image cache). Should it?

**Comment by zcorpan** [comment]
I'd prefer "must" over "should" and also clarify what modifications means; in particular setting it to the same value as the previous value

**Comment by jeisinger** [comment]
I guess in my test case, I had the image already in the cache then.

I don't have a strong opinion either. Not making it a relevant modification is easier, as this won't require implementation changes :)

**Comment by annevk** [comment]
If it only has an affect when changing `referrerPolicy` later than we should probably not do it. The only reason I changed my mind was https://github.com/w3c/webappsec-referrer-policy/pull/35#issuecomment-213271557 but if that's not affected I think we're okay.

**Comment by jeisinger** [comment]
ok, and back to *not* a relevant mutation...

**Comment by zcorpan** [comment]
LGTM :-)

**Comment by yoavweiss** [comment]
belated LGTM :)

**Pull request merged**
